use std::path::{Path, PathBuf};

use clap::Parser;
use codegen::{triple::get_triple, generate};
use error::CompilerError;
use preprocessor::preprocess;

pub mod error;
pub mod fs;
pub mod preprocessor;
pub mod codegen;

#[derive(Parser, Debug)]
#[command(version, about, long_about)]
struct CLIArgs {
    /// The .c files to compile
    #[arg(required=true, num_args=1..)]
    files: Vec<PathBuf>,

    /// Compile without linking to an executable
    #[arg(short)]
    compile_only: bool,

    /// Output file path
    #[arg(short, value_name = "PATH")]
    output: Option<PathBuf>,

    /// Verbose logging output
    #[arg(short, long)]
    verbose: bool,

    /// Define a macro for the preprocessor
    #[arg(short = 'D', value_name = "MACRO")]
    defines: Vec<String>,

    /// Include the given directory in the include search path
    #[arg(short = 'I', value_name = "PATH")]
    includes: Vec<PathBuf>,

    /// Only run the preprocessor and send to STDOUT
    #[arg(short = 'E')]
    preprocess_only: bool,

    /// Don't run the assembler; instead send emitted assembly to STDOUT
    #[arg(short = 'S')]
    emit_assembly: bool,

    /// Print the AST generated by the parser
    #[arg(long)]
    ast: bool
}

fn main() -> Result<(), CompilerError> {
    let args = CLIArgs::parse();

    println!("{:?}", args);

    let files_preproccessed = args.files.iter().map(|ref s| preprocess(s));

    if args.preprocess_only {
        for file in files_preproccessed {
            println!("{}", file?);
        }

        return Ok(());
    }

    let triple = get_triple();

    println!("Compiling for {}", triple);

    generate(triple, Path::new("a.o"));

    Ok(())
}
